### ISSUE TITLE
Find 7 rival and similliar software to compare

### ISSUE THREAD

**Issue by smolijar** [grissius/markup-editor-ui#18]

**Comment by smolijar** [comment]
# SimpleMDE
Embedovatelná webová komponenta. Editace zdrojáku md, life prevew.
https://simplemde.com/

**Comment by smolijar** [comment]
# AsciiDoctor FX
Javovska app pro psani AsciiDoc komplexnich dokumentu (nevenuje se editaci jednoho file, ale mnoha)
http://asciidocfx.com/

**Comment by smolijar** [comment]
# AsciiDocLIVE
Webova appka, asciidoctor editor. Neni zatim embeddovatelny vypada.
https://asciidoclive.com/edit/scratch/1

**Comment by pchmelar** [comment]
# StackEdit

Webovy opensource MD editor
https://stackedit.io/

**Comment by slowbackspace** [comment]
https://typora.io/
https://dillinger.io/ (webove, markdown only)

https://pandao.github.io/editor.md/en.html

> Support Standard Markdown / CommonMark and GFM(GitHub Flavored Markdown);
> Full-featured: Real-time Preview, Image (cross-domain) upload, Preformatted text/Code blocks/Tables insert, Code fold, Search replace, Read only, Themes, Multi-languages, L18n, HTML entities, Code syntax highlighting…;
> Markdown Extras : Support ToC (Table of Contents), Emoji, Task lists, @Links…;
> Compatible with all major browsers (IE8+), compatible Zepto.js and iPad;
> Support identification, interpretation, fliter of the HTML tags;
> Support TeX (LaTeX expressions, Based on KaTeX), Flowchart and Sequence Diagram of Markdown extended syntax;

**Comment by pchmelar** [comment]
# Sublime / Atom / VS Code / Brackets
.. klasika, kazdy zna
Vcetne rozsireni pro syntaxi a live preview moznosti

**Comment by smolijar** [comment]
# Caret
Proprietarni desktop markdown editor
https://caret.io/

**Comment by pchmelar** [comment]
# react-md-editor
React komponenta, zatim asi pouze zakladni funkce..
https://github.com/JedWatson/react-md-editor

# ~react-markdown~
~Dalsi React komponenta, moznost konfigurace pri embedovani
https://github.com/rexxars/react-markdown~
> *EDIT* @grissius
> Pozor, tahle knihovna `rexxars/react-markdown` neni editor. To je parser markdownu do HTML reprezentovany React componentama. Sama o sobe ta knihovna neni pouzitelna jako editor. Tj. nema to podle me zadnou wrapper componentu, kterou bys mohl vykreslit v DOMu a pak si vzit jeji value. 
https://github.com/rexxars/react-markdown/blob/master/demo/src/demo.js
Tohle je zdrojak toho dema. Coz je fakt jen krabice, ktera ma zadratovanej initial value v sobe. Demo slouzi jen k tomu, aby sis mohl prohlednout ten parser.
Proto mi to mozna pripada jako nestastny tohle. Neni to editor, je to wrapper pro markdown parser.

**Comment by smolijar** [comment]
#  Google Docs / OpenOffice Writer / LibreOffice Writer / MSO Word
Je to sice mozna mimo misu trochu, ale je to zase protipol k generickejm editorum typu sublime. Mohlo by tam byt neco inspirativniho v UI, protoze stejne jako Markup editor se soustredi na obsah (az na to ze tyhle veci se soustredi taky na barvicky :smile_cat: )
