### ISSUE TITLE
Tasklist graph

### ISSUE THREAD

**Issue by smolijar** [grissius/markup-editor-ui#8]

**Comment by smolijar** [comment]
![](http://www.plantuml.com/plantuml/svg/TLIzRjim4Dxr58TqA-07S15uQDEWIzC21JguxN0MBvOgYXH8IcuTv0tQ1mWoUUpWgNEoo7wlyaSIvPzwC7Htttrtz_58NUIYGeKbP2ZOIkN6a02ZQahq42gba6ccP4d74MtG4Dmb0AynBPPAreAzaLogoyltc8lP35vCfzFa7kml-VBo6qnKlipCP0PDJYkT-F_ej8Wa2PmNxpWsejt2MYuKhcM3gJNAzY_xUG6eGpuCPLmBNUASAVbTDkqJ51RjmLhMAgK8kMat6IS6J1PrISBK7bKfSgp_Om84qUKrn3Y1fWNvHBEIgUGkpzU1YHqbadLVtXiRYSWXEtmSuaQ-yunTzlsWszphHKwwnY9bnjlj_fbsltFVAvKBEu2Jon-7PV0UHYpE_RRpn8I3y7NDkKuLaV20sy6qa1xjcGyYqJYi6Zk_GhxVk4EM-sSXjScxitUp-4goChaK6kxyEWtzNENQA4nT36vj0OzbqNbjVHPzv7a57_SFL0c2xCocVHL-rq0W76v1BBlxrMurHzW_j1j6XQ_AnMXxa6DfypQEsz2FRijM2gi8-b0RdelGiWpVCVYf8ixJZD90hWVpT1glgRi-O7iO6QxQoEnAZ3oHTEJiL-DKn3xY1-sDRgJUZ7Fqdb7dyRXliCcNc8RP1JRZE_ovVLhi7bNGjWZ2BQMHX_hCaGLrtQL4qVwnnzzkre5H4weqi-0-RpoqZvqPU5HZw3tmdBrWzZsePBDxxDwaZ7YLz6zQl-D9k76JupUlhfnKOQEJVhDFKDQsqYHEddCnNz7znUW_)

[Zdrojak](http://www.plantuml.com/plantuml/uml/TLIzRjim4Dxv58TqA-07I14OGPi6NPeMAD31RGTQl5YgA58WARbra3Te7o38vB63fyx98lkzoXz9f7_gmT3TVVVTtSSZBxMXoZGL9xeiH4qLhI2dWYrLOGmACAh195H98RDSoGeF8vR78DmHWDSqAnTADeAzaLogYultj13JARmuFpydzs1_vClBRp1HnI8taocq1IuryV_HQH641CwpTvosejl0IiuLNScMPjQekh_ivnbG7V9XBEDQw1DdJCdliksUeBHe3zQoKHb6o4stpZaoOB9iAXIcyQXQeMFz7nDG47rUYumZQ9oZJpHBcKdkydmTcDXH8bd_vRsnaOWSiyF7FYxndMRii-z7tMPUBtJIjHOfSzvjTi-u_LtuNh6Qsm6SNFuuB8FtC6HnxhUz9oRiXQyRpdMc48K7t8wcXGnepxmNYSP-rTZv5UMxjJjakNiMKfkYFtitYwyaQrD8eU7EhzFOprMXZQAPYy6jBU2nB3glhS-Y3poluEFk0Mk1a9_OjA_2xne82ljR4CjkVtKRpIdi7hermz9NvIBP7iffPVFMZjlWZtxBbehM4VIXCRmGeMKPlcFmKusSPpbcWLoFvl4qNbDtVS3sa1YkMcBs9H9F94sSmseSYpX4_A23qOyqc76EmPDq7e_xXhR5WcPXTa7Rz0v_xfxcsqSLj2s3S0jfvBu-Cyg2kkvIKj7ziSVVhLU1KIDLMMx1Gruwj8-T63YfCVOUU4vUCFiUrBBTFlPlKewy9iERDkmu2JTkSlZcDRMJAcmq6JRx26LjAmrnyfoA-OhkBucIInJClUt_0000)

**Comment by pchmelar** [comment]
Za me OK, rekl bych ze to je spravne dle konzultace s p. Hunkou

**Comment by smolijar** [comment]
Pokud bychom se dohodli, ze je vhodne udelat napovedu tutorialem, tak by pres ni mel mit cestu puvodni node (pri prvnim spusteni treba ze se pusti).

**Comment by pet-e** [comment]
Co je výchozí zobrazovací mód?

![taskgraph](http://www.plantuml.com/plantuml/png/TLIzRjH04Exz52leaEu14aL1WX3H490G50afzhoJi_5wnzfT-o0eFGKyG9JgIeghg9F6T-_5_jcxlZiQopFppJU_EwegHKCbhKb11LlAKciGHCiMCZMQQXIO5n9hsBKeJJMG7naXhsXUBIIsWhr6ZlBav1qjnUafUNvqT9JTPLSlhibCbej2pqv9Ly9IPUuRbGQHPPxlsLjEEz6loItE9Rt5ZkP6gFk_xFipGfNt9sC86puuNZA9Nx7h7qbbq0wii9KvHCX5loeuCCAmQciGkdMeHe9b_HyJeKG4lmuO1w9W3ivHBp57RlrS738pfKIoyEUqCP687BtzpnINw0up1k-xiM-NhbzWMzSP91QyNs-VOFExTBb2FJS5s7QvSHW6fs70OjrlWYOwJCpdBUSgbm320Mv6qK06j6EUMA8mZHepFwDykx93nksJGANBC7jRYuk4ZIvHg7JOPwNIakPMJsuCkSEng3mtEeFUqHoJ3zjxQ0IGui2MVH5kpuYWPBe1CUpcLxzMd9BjVRzYKBceN2IRGpcjZT_ASclu5ZPiAMaJGUzRpKlXKqR_7uqV6-0yBo3tv6eKaoscytxDAchMkE7Rdo6SW-V88CUwuM1Btc-06u5zRSIadGWsmKGCMIMQc4UYd4PB3CEAxQKp6FOdDLXu2Wjz6yJOh46Jj2VkqmNjoWNDVOC5xTAz-Tm_pZSFqW-myjDPeCRf42ufyoEqhvwA_e_PiNvrwnaLK9aN1ZpufMrojWETI6ACkNkUWo_O79m6kyr3E7e5y2QpdsFpI4ngt6Am4lWoARgGFcV3Od8DjPKrNS2dXYDbMV9FTecouIGFJpJp1sEsUxBRnWx2FyXiU9XxA2ERncUs-OTiOpq7hTCyhyB95337SFMk9wMC5Fy0)
[src](http://www.plantuml.com/plantuml/uml/TLMzRjim4Dxv54Iw5V0390ZIe4s3BaqB5EsGD0CjNYnL54-WABbDaRr3-m119eyTF6LE5jdlLVx9f6nt4NXtttttI-gqqKpfjXAaAGjPCyKgcZF9vwhG6YJLgeN4LA74B5TOmRR5y6YWFmcbhrbMpXIsahz1WUhu-3qhvCa9VN5uU4ZkoDNBQpfHnIpNanFQ5J1lYFj6fK4GulaEtWdMoNv9Rt6gs2rsB3D2rJ_o7mUKDTwVRaBOyC7naYlyXbt_H4k3Tk06MvL1X5pqYrm0fnpBjWAfMuUg5LZM_p5HHcNmwu0Be0rCmJdgEMOeh9-BGoUcb4WMJauR4ud8ZRS_Z769RZzZyBxRzEtIzGjiwpg3n5pqo_KphFuKBbUefgO0sout3iFWD1nuhFjjq4I7aVcy5QB9581qW9kDQ203sZ6FB54OHusPdp6nNjWXu_fPOgEBC7jRYuk4jIvGDkcmpuf6AvPPFRqnv0x7e_BSw0nwItD4FwxlePP0yprRzbMwFQEIqV46nB2ht_so4Ookx_i5Xz955JBP72POPVmMbbl3zx1XSyNg2FhGQb58dpBwSpH-ga68B8VCapSRCTbYDksNl6HcZMkn_XN2ENY673AiQW6svDq6k17OsqPDsebW4qp4a5MYYNaaod6qn32is4uwWs5tKeD5fB3Gjq6CpHeqINlYFbsmhfYnp3TOiYxTco_zqtJreFm0Ip-T6MeS3-6ISJz2U-kPxF-Q7UiNjvwn0QQot807lxHDphQd4qcCJUwUP-yDDWzEZTtg8JnwEOYQsC-HkIGcDM4nM4fybHITAv-pOJ6vXjgAYitWSosGSPASwJOH6PxauOeI_s1Cjf_ijhQ3y1UI31Tp1sLaqtXYcx_FjgbdhtMSvrLuCYLCCRnwrwDI8WKv1Sdjd-qV)

**Comment by pet-e** [comment]
Tutorial je fajn pro prvni spusteni (velmi hezky je lehky overlay pres cely editor a zvyrazni se pouze cast o ktere se mluvi s kratkym popiskem "tady se pise kod", "tady si muzete zobrazit outline", "kliknuti do preview umistni kurzor do patricne casti zdrojaku", atp.)
Ale napoveda je imho potreba vzdy (tudiz si myslim, ze bud napoveda, nebo jak napoveda tak tutorial).

**Comment by smolijar** [comment]
Vychozi zobrazovaci mod je asi dvousloupecek. Mohl by tam byt inicialni puntik flow v ramci stav skupiny.

1. Nechapu proc je u napovedy "modalni okno?" s otaznikem.
2. Napovedu bych tedy udelal jen jako nejakej modal. Pokud nam zbude cas tak muzeme udelat tutorial.
3. Nahrani obrazku by podle me nemel vubec bejt modal. Kdyz tam chces dat obrazek, tak se nechces hrabat na nejakym ulozisti na serveru. Stejne jako to dela github/gitlab, dragndrop by imo mel vygenerovat link a ten vlozit. Vubec bych tedy do tohoto diagramu nezahrnoval.
4. Nechapu proc je navic "[source nebo twocol]" u vsech navratu do skupiny se predopklada navrat do posledni pouzite.

**Comment by pet-e** [comment]
1. To jsem se mel zeptat tady a ne v diagramu :), ale uz jsi odpovedel v 2.

3. Ok, nicmene github ma tlacitko "selecting them", ktere ti otevre modal.

4. Protoze graphviz neumi dobre pozicovat labely. Nicmene per 3 to odstranuju.

![](http://www.plantuml.com/plantuml/png/TLIzRjim4Dxv54Iw5V0390Woj6dGfMc10XtSTg35YwMAuWaa9RSEidTe7o38vB63fyx98lkzoXz9f69t4NJVVVV3xuxKPI5hfbX5SoRvIXN6WAH6DK3qwAfGOfOhhE2vHnjcWDuIIb-nh5mgR2H_ZGBL-VaxLiYB2_hYzFIKt97FBx_IcIgMkPbTqBQ0bIR-6q7B82JaEtahM2kxBLtZGh4rjYopHjNzvJzEADCXdeubNFa-SCuLViEsUwIbPNkonaPb42dNtIONm2d7igb0ciQpQWKkw_yoKKPb7zS25q0rBC07cXLcA6pSv8GZ6ghJcSLYYVxFex6zo1oZmy-Kbs37C_RHTwEQSwyYE45RoyHSTDlz4-n-5_u4K2tiiMw78zWC7k70enflUYG6JDnNZH0wKm3I4sv6qr86jiyyyKHZMZLsVid4VkD6Z_idYTeK_KQui_XAM9i2fKvNuBBGHh7CuVJ69lSy7i4hYrdsC-ICVjZVGos1vaTsxulqsqSbezEzY6Ltlxgj5epkxxiDXz9N5JBP9oPOPUCsBhU1x_tUhHIh8-bzOqGXGyiO_gFpOmr2P3ba8RaUpMItsQBRyfBPvQx5_cTVpjCpv91XLGjmHpuKm8_0tK5gsquCrs1YzbqbIEmZ0QVL4iUmOWVj38x3IGqUaT9wtGOpYZKWYJnndwvPMonP5WIMh4ttvbFtkDWzg330CandYGQdGvWp7aRetW8ckpzsnxhDEcJKm5IMM_8GbyhaVKUKI6gClOSyHs-mVOPgR7SF_LEOWwY9-vpPIs9R4uw3fKH2XWTsk5eaNFJPymUugPs0uIAHuK8TiAnj1IDEj6E-iO_e_GS0)
[src](http://www.plantuml.com/plantuml/uml/TLMzRjim4Dxv54Iw5V0390Y2e4s3BaqB5EYGjWDDNYnL54-WABbDaBr3-m119eyTF7LE5jdlLVv88cMxYw7xxhiVVdUapsl3j6bAIUeYLnNJhAGPKsAfSsD0KQCRI5mbAkIPnX9sFJQF0Nf7A7t5UB7Gs2Zn6YNgqzDtB5TdP_J5yV4nkIUVNtwbCvqlCZCxesqEovhutmXQ1Y4Xtz5RoLhLhUajpZMxnPPnQvJTN_7ZYB8wnDEnX2lV1ruBZT-mxPveOTcUN6EZEKJALRVA90Wgi6XAKARnh4g3o_g_J9HHrSUr82JG6kRW0yqIEKeRDpdXY8RgT6QnMAB_ycXiBpB7wF0nvINOuOnzzFsevhLN4PoWhMLY9hlrzXasltD_0YZdzbXtmn5i1ey8456DDpqI0oRkoqRAcci0vGatesaf0zjdddYYCQqQExzWShjoeyVjiyBQvFr6kBFuIbYP75MThi15NXlDkCFfZKtkUIA2bnQpx1taX7xOFa2bW6O7Tk-Byjj75QFJlOXbDx-wTIqPtJvqAm65hofLiazCijB6hLnk0z_xlLjgLaNI-yR8N8MMCNn7vySAfEGPy92y7irajzcyMuk2sUMkvFPdNyxJEGhWM5OIt97t1V0ZS7UGshOJmpMOc7rN2HBxIC1fjSGnhDXUEuDZVrA3HwQqNhV1Z68DI29FtAShrkOBneF0YhNftdpgdkQRHnq6M8JfBD3WT0ZNJ8GHkhU0gUwFtR5kTHiori0qponvY4jbyhu3IYGrnjv3deCts3v35RQRn_ufp41MnFsSs4jYMvEEWuL2GeO7ThXQ95pqsUu3t5HEm72Ho72XzbZMje8H9zeXtzX7uZq79Un_p3y0)

**Comment by smolijar** [comment]
@pet-e Co je _Nabidka doplnovani_?

**Comment by pet-e** [comment]
Doplňování kódu... Vyskočí nabídka s možnostmi.

-----Original Message-----

**Comment by smolijar** [comment]
Ok, to nepatri k moznostem zobrazeni. Bud bych to nechal jako ze to bereme implicitne soucasti editace (jako multicursor), nebo udelal skupinu editace. Pojmenoval bych to asi _autocomplete_, i kdyz je to anglicismus tak je to podle me z toho zrejmejsi.

Jsem spis pro vypusteni z taskgraphu a jen to pak zobrazit v nejakym editacnim wireframe mimochodem.

**Comment by pet-e** [comment]
Ok, ignoruj to.

From: Jaroslav Šmolík
Sent: Thursday, October 26, 2017 12:10 PM
To: grissius/markup-editor-ui
Cc: pet-e; Mention
Subject: {Disarmed} Re: [grissius/markup-editor-ui] Tasklist graph (#8)

Ok, to nepatri k moznostem zobrazeni. Bud bych to nechal jako ze to bereme implicitne soucasti editace (jako multicursor), nebo udelal skupinu editace. Pojmenoval bych to asi autocomplete, i kdyz je to anglicismus tak je to podle me z toho zrejmejsi.
Jsem spis pro vypusteni z taskgraphu a jen to pak zobrazit v nejakym editacnim wireframe mimochodem.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/grissius/markup-editor-ui","title":"grissius/markup-editor-ui","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/grissius/markup-editor-ui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@grissius in #8: Ok, to nepatri k moznostem zobrazeni. Bud bych to nechal jako ze to bereme implicitne soucasti editace (jako multicursor), nebo udelal skupinu editace. Pojmenoval bych to asi _autocomplete_, i kdyz je to anglicismus tak je to podle me z toho zrejmejsi.\r\n\r\nJsem spis pro vypusteni z taskgraphu a jen to pak zobrazit v nejakym editacnim wireframe mimochodem."}],"action":{"name":"View Issue","url":"https://github.com/grissius/markup-editor-ui/issues/8#issuecomment-339618657"}}}
