### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by smolijar** [grissius/markup-editor-ui#9]

**Comment by smolijar** [comment]
S Hunkou jsme se dohodli, ze udelame wireframes pro ty tri zakladni pohledy a pak si jeden vybereme a pouze na nem ukazeme ty male dekorativni veci (pridani outline, cilsa radek etc.)

Jsem pro se dohodnout na nejakym super-combo wireframe, kde budou naplacany vsechny komponenty. Z toho pak nasekame nekolik wireframes pro vysledek s komentari atd.

Muzete editovat v browseru https://webdemo.balsamiq.com/, je tam moznost import JSON.

Prosim o pripominky.

![](https://pasteboard.co/images/GQHuuQr.png/download)

https://pastebin.com/BXJPZ4Ua

**Comment by slowbackspace** [comment]
Možno je to zbytočné, ale nechceme tiež urobiť jednoduchý wireframe pre embedovaný editor? (asi niečo ako textarea s buttonom na prepnutie do full editoru?)

**Comment by smolijar** [comment]
Ten bych potom udelal. Chtel jsem se dohodnout na tomto. Pak z nej neco orezat a treba ho ukazat jako embedded.
Jde mi o to, ze velmi podobny pohled bude na temer vsech wireframes a nemuzeme vytvorit referenci na tu komponentu v balsamiqu, ale jen kopie, proto jsem chtel se shodnout na jadru, ktere pak s drobnymi modifikacemi posleme do dalsich pohledu.

**Comment by pchmelar** [comment]
Pridal jsem SearchBar, jinak me nic dalsiho nenapada..

![new mockup 3](https://user-images.githubusercontent.com/3842139/32144202-7600b2da-bcb5-11e7-9234-fb374cf46f91.png)

https://pastebin.com/mPfe6sxq

**Comment by pet-e** [comment]
Chceme tam teda ted uz vsechny ty veci a ficury?

Rovnez kdyz ted vidim ocima ten search... asi spis budem chtit search & replace.

Ad command palette... chapu to tak ze to bude rada tlacitek ci co?

![welcome](https://user-images.githubusercontent.com/33096492/32146058-437bca26-bcd2-11e7-83fc-3c793b98ceb0.png)

https://gist.github.com/pet-e/8d3ad8abe692e118fe027deaba8fb5ed

**Comment by smolijar** [comment]
Command palette button, mel jen v mych ocich otevrit paletu, ktera je uz nakreslena nahore. Nevim uplne jestli chceme vzhledem k charakteru uzivatelu pridavat tlacitka jako je bold, italics etc. Podle me jsou zbyecne.

**Comment by smolijar** [comment]
Tedy mysleno cely ten radek @pet-e. To je spise _toolbar_, ktery je naopak zvyklosti pokud je pritomen umistovat nahoru imo.

**Comment by pet-e** [comment]
Bold/Italic jsem dal jenom jako prikaz, ale videl jsem tam ficury jako "manipulace s tabulkami"... trebas jako mas ve Wordu vkladani tabulek, tak si muzes vyselectovat jak velka ta tabulka je... ale vlastne nikde neni moc receny jak to bude vypadat (coz asi resime tady, ze :))

**Comment by smolijar** [comment]
Ok. Tyhle moznosti by primarne mely by imo dostupne pres command palette/zkratku. Nechces pri bezny editaci kvuli bold klikat na tlacitko mysi. U tabulky je to otazka, ale i takl muze byt pres command palette.

Co se tyce toolbaru, tak to v zasade neni spatny napad, ale je to uz na jinou cilovku, tj pro lidi, ktery neznaji syntax/nebo jsou zvykly na klikatka. Takze jsem klidne pro to zahrnout, s tim, ze kdyz to budes pouzivat, tak to bude jako option, jeslti tam toolbar zobrazit, cimz by mohl byt ve finale editor vztricnejsi pro BFU. Jediny tradeoff by byl, ze by zabiral misto, ale veskere ovladani pres klavesnici bude stale dostupne.
Jsem pro tedy tam toto napsat a zobrazit ho na jednom wireframu treba s timto komentarem.

**Comment by smolijar** [comment]
Zanechal bych tlacitko `Command palette` aby bylo mozne paletu vyvolat i klikem. (To je trochu technikalie: Samotna komponenta muze obsluhovat zkratku na paletu, ale pokud se ztrati focus tak by to musel handlovat globalni event na window. Ten v ramci komponenty nechci implementovat, protoze je to prasovina, takze to spoleha na to, ze to pripadne nastavi ten co to bude embedovat. Pokud ne, mela by tam byt tato moznost.)

Autosave timestamp se mi libi, ale asi to nebude link, nebo?.

**Comment by smolijar** [comment]
Nemel by byt gotoline soucasti jiz neceho exitujiciho? Tedy bud v inputu pro commandpalette, nebo dole jako bude search?

**Comment by smolijar** [comment]
@pet-e dekuju za SQL code block a ocenuju to. Vim, ze je s tim docela srani v tom balsamiq markupu :D Puvodne jsem to chtel udelat obrazkem ten syntaxhl, ale to bychom nemohli exportovat do JSON.

**Comment by smolijar** [comment]
![markup](https://user-images.githubusercontent.com/24388536/32178931-55b6611c-bd8e-11e7-9e6e-3553fd5767c6.png)
https://pastebin.com/16i2Jp4R
